bioweb/bioweb/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('', include('mainsite.urls'), name='mainsite'),
    path('users/', include('users.urls'), name='users'),
    path('admin/', admin.site.urls),
]

bioweb/mainsite/urls.py
from django.urls import path,include

from . import views

app_name = 'mainsite'

urlpatterns = [
    # 主页
    path('', views.index, name='index'),

    # 显示两中计算方式的入口界面
    path('cal/', views.calculation, name='calculation'),

    # 上传图片并计算-中轴线、宽度、半径计算界面
    path('cal/1', views.cal_dia_centerline_width, name='cal1'),

    # 上传压缩包计算中轴线、宽度、半径计算界面
    path('cal/1/compress', views.cal_dia_centerline_width_compress_fake, name='cal1compress'),
    path('cal/1/dia_compress_real', views.cal_dia_centerline_width_compress, name='cal1compress_real'),


    # 上传图片并计算厚度的界面
    path('cal/2', views.cal_thickness, name='cal2'),
    # 上传压缩包计算厚度的界面
    path('cal/2/compress', views.cal_thickness_compress_fake, name='cal2compress'),
    path('cal/2/thick_compress_real', views.cal_thickness_compress, name='cal2compress_real'),

    # 下载url
    path('cal/download', views.success_download_excel, name='download'),

    # 上传成功界面
    path('cal/success', views.success, name='success'),


    path('show_uploade_progress', views.show_uploade_progress),

    path('upload_compress_1', views.up_load_compressfile_1, name='upload_compress_1'),
    path('upload_compress_2', views.up_load_compressfile_2, name='upload_compress_2'),
    path('show_progress', views.show_progress),

]

bioweb/users/urls.py
from django.urls import path,include
from django.contrib.auth.views import LoginView
from . import views


LoginView.template_name = 'users/login.html'
urlpatterns = [
    # 注册
    path('login/', LoginView.as_view(), name='login'),

    # 注销
    path('logout/', views.logout_view, name='logout'),

    # 注册
    path('register/', views.register, name='register')

]
app_name = 'users'

bioweb/mainsite/models.py
from django.db import models


# Create your models here.

class IMG(models.Model):
    # 图片数据库模型
    img = models.ImageField(upload_to='img',max_length=10000)
    name = models.CharField(max_length=50)

bioweb/mainsite/forms.py
from django import forms

class FileFieldForm(forms.Form):
    file_field = forms.FileField(widget=forms.ClearableFileInput
                (attrs={'multiple': True}))

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

bioweb/mainsite/views.py
from django.shortcuts import render
from django.http import HttpResponse,FileResponse
from .models import IMG
from .forms import FileFieldForm,UploadFileForm
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.urls import reverse
from django.views.generic.edit import FormView
from django.contrib.auth.decorators import login_required
import os
import xlwt
import cv2
import numpy as np
import time
from . import bio_ClassAndFunction
import zipfile
import rarfile
import shutil
import sys

def index(request):
    # 主页
    return render(request, 'mainsite/index.html')

@login_required
def calculation(request):
    # 显示两种尺寸计算入口的界面

    return render(request, 'mainsite/calculation.html')

@login_required
def cal_dia_centerline_width(request):
    # 计算中轴线、半径和宽度的界面

    # 清除cache目录下的文件
    cache_path = "/home/zyf/project/bioweb/bioweb/cache/"
    shutil.rmtree(cache_path)
    # 创建新的cache文件夹
    os.mkdir(cache_path)

    if request.method != 'POST':
        form = FileFieldForm()
        print(form)
        print('\n')
    else:
        form = FileFieldForm(request.POST, request.FILES)
        files = request.FILES.getlist('file_field')
        print(form)
        if form.is_valid:
            for f in files:
                destination = open(os.path.join("/home/zyf/project/bioweb/bioweb/cache",str(f)),'wb+')
                for chunk in f.chunks():
                    destination.write(chunk)
                destination.close()           # 将上传的文件写入到本地
            print("写入到本地--完成")
            bio_ClassAndFunction.cal_dia()    # 调用处理函数
            print("处理完成")


        return HttpResponseRedirect(reverse('mainsite:success'))

    return render(request, 'mainsite/cal_dia_centerline_width.html')


@login_required
def cal_dia_centerline_width_compress_fake(request):
    return render(request, 'mainsite/cal_dia_compress.html')

@login_required
def cal_dia_centerline_width_compress(request):
    # 计算中轴线、半径和宽度的界面  压缩包处理界面
    print('begin to calculate')
    # 计算厚度  压缩包处理界面
    global num_progress
    global eta_time
    global imgshow
    num_progress = 0
    imgshow = None
    last_file = None
    last_2_file = None
    last_3_file = None
    eta_time = 0
    i = 0
    filenum = 0
    for root, dirs, files in os.walk("/home/zyf/project/bioweb/bioweb/cache"):
        if dirs:
            for dir in dirs:
                path = os.path.join(root, dir)
                filenum += len(os.listdir(path))
        else:
            filenum = len(files)

    support_img_file = ['jpg', 'png', 'jpeg', 'bmp', 'tif', 'gif', 'webp', 'psd']
    ws = xlwt.Workbook(encoding='utf-8')
    w = ws.add_sheet('中轴线、宽度、半径信息', cell_overwrite_ok=True)
    w.write(0, 0, '图片名')
    # w.write(0, 1, '厚度')
    w.write(0, 1, '半径1')
    w.write(0, 2, '半径2')
    w.write(0, 3, '中轴线长度')
    w.write(0, 4, '宽度1')
    w.write(0, 5, '宽度2')
    w.write(0, 6, '宽度3')
    w.write(0, 7, '宽度4')
    w.write(0, 8, '宽度5')
    w.write(0, 9, '平均宽度')
    excelname = '/home/zyf/project/bioweb/bioweb/cache/result.xls'
    row = 1
    for root, dirs, files in os.walk("/home/zyf/project/bioweb/bioweb/cache"):
        if dirs:
            # 如果有其他文件夹 就遍历这些文件夹
            for dir in dirs:
                path = os.path.join(root, dir)
                file_sorted = sorted(os.listdir(path))
                for filename in file_sorted:
                    fileformat = filename.split('.')[-1]
                    if fileformat.lower() in support_img_file:
                        start = time.time()
                        print(filename)
                        imgname = os.path.join(path, filename)
                        print(imgname)
                        try:
                            src = bio_ClassAndFunction.image(imgname, pixelsPerCM=81, referenceLength=20)
                            part1, part2, part3, part4 = src.image_segmentation()
                            proce1 = bio_ClassAndFunction.ProcessMethod(part1)
                            diameter = proce1.cal_diameter(filename)
                            proce2 = bio_ClassAndFunction.ProcessMethod(part2)
                            midAxis, width = proce2.cal_MidAxis_Width(filename)
                            print(diameter[0] / src.pixelsPerCM)
                        except:
                            # 处理出错 则跳过该图像
                            w.write(row, 0, filename)
                            w.write(row, 1, "该图像或文件无法处理")
                            w.write(row, 2, "可能原因：香菇尺寸过小，背景不够清晰;或者文件格式不正确")
                            continue

                        else:
                            w.write(row, 0, filename)
                            w.write(row, 1, "%.2f cm" % (diameter[0] / src.pixelsPerCM))
                            w.write(row, 2, "%.2f cm" % (diameter[1] / src.pixelsPerCM))
                            w.write(row, 3, "%.2f cm" % (midAxis / src.pixelsPerCM))
                            w.write(row, 4, "%.2f cm" % (width[0] / src.pixelsPerCM))
                            w.write(row, 5, "%.2f cm" % (width[1] / src.pixelsPerCM))
                            if len(width) > 2:
                                w.write(row, 6, "%.2f cm" % (width[2] / src.pixelsPerCM))
                                if len(width) > 3:
                                    w.write(row, 7, "%.2f cm" % (width[3] / src.pixelsPerCM))
                                    if len(width) > 4:
                                        w.write(row, 8, "%.2f cm" % (width[4] / src.pixelsPerCM))
                            w.write(row, 9, "%.2f cm" % (np.array(width).mean() / src.pixelsPerCM))
                            print("\n")
                        row += 1
                        i += 1
                        imgshow = last_file
                        num_progress = format(i / filenum * 100, '.1f')
                        eta_time = int((time.time() - start) * (filenum - i))

                        delfile = last_3_file
                        last_3_file = last_2_file
                        last_2_file = last_file
                        last_file = filename
                        print('last two file', last_2_file)
                        print('last file ', last_file)
                        print('file ', filename)
                        # del last file
                        if delfile:
                            delroot = "/home/zyf/project/bioweb/bioweb/static/vis/cache"
                            delfile_path1 = os.path.join(delroot, "mid" + delfile)
                            os.remove(delfile_path1)
                            delfile_path2 = os.path.join(delroot, "dia" + delfile)
                            os.remove(delfile_path2)

        else:
            file_sorted = sorted(os.listdir("/home/zyf/project/bioweb/bioweb/cache"))
            for filename in file_sorted:
                print(filename)
                print(row)
                imgname = "/home/zyf/project/bioweb/bioweb/cache/" + filename
                fileformat = filename.split('.')[-1]
                if fileformat.lower() in support_img_file:
                    start = time.time()
                    print(imgname)
                    try:
                        src = bio_ClassAndFunction.image(imgname, pixelsPerCM=81, referenceLength=20)
                        part1, part2, part3, part4 = src.image_segmentation()
                        proce1 = bio_ClassAndFunction.ProcessMethod(part1)
                        diameter = proce1.cal_diameter(filename)
                        proce2 = bio_ClassAndFunction.ProcessMethod(part2)
                        midAxis, width = proce2.cal_MidAxis_Width(filename)
                        print(diameter[0] / src.pixelsPerCM)
                    except:
                        # 处理出错 则跳过该图像
                        w.write(row, 0, filename)
                        w.write(row, 1, "该图像无法处理")
                        w.write(row, 2, "可能原因：香菇尺寸过小，背景不够清晰;或者文件格式不正确")
                        continue

                    else:
                        w.write(row, 0, filename)
                        w.write(row, 1, "%.2f cm" % (diameter[0] / src.pixelsPerCM))
                        w.write(row, 2, "%.2f cm" % (diameter[1] / src.pixelsPerCM))
                        w.write(row, 3, "%.2f cm" % (midAxis / src.pixelsPerCM))
                        w.write(row, 4, "%.2f cm" % (width[0] / src.pixelsPerCM))
                        w.write(row, 5, "%.2f cm" % (width[1] / src.pixelsPerCM))
                        if len(width) > 2:
                            w.write(row, 6, "%.2f cm" % (width[2] / src.pixelsPerCM))
                            if len(width) > 3:
                                w.write(row, 7, "%.2f cm" % (width[3] / src.pixelsPerCM))
                                if len(width) > 4:
                                    w.write(row, 8, "%.2f cm" % (width[4] / src.pixelsPerCM))
                        w.write(row, 9, "%.2f cm" % (np.array(width).mean() / src.pixelsPerCM))
                        print("\n")
                    row += 1
                    i += 1
                    imgshow = last_file
                    num_progress = format(i / filenum * 100, '.1f')
                    eta_time = int((time.time() - start) * (filenum - i))

                    delfile = last_3_file
                    last_3_file = last_2_file
                    last_2_file = last_file
                    last_file = filename
                    print('last two file', last_2_file)
                    print('last file ', last_file)
                    print('file ', filename)
                    # del last file
                    if delfile:
                        delroot = "/home/zyf/project/bioweb/bioweb/static/vis/cache"
                        delfile_path1 = os.path.join(delroot, "mid" + delfile)
                        os.remove(delfile_path1)
                        delfile_path2 = os.path.join(delroot, "dia" + delfile)
                        os.remove(delfile_path2)

bioweb/mainsite/templates/mainsite/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" context="IE=Edge">
    <meta name="Viewpoint" context="width=device-width, initial-scale=1">
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/docs.min.js"></script>
    <style>
        .progress-div{
            background: rgba(0, 0, 0, 0.03);
            width: 1000px;
            height: 140px;
            padding: 60px 20px;
            visibility: hidden;
        }
        .progress{
            margin: 0;
            /*position: fixed;*/
            /*top: 100px;*/
            /*left: 20px;*/
            width: 100%;
        }

    </style>
    <title>香菇尺寸计算</title>
    {% load static %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>

  <nav class="navbar navbar-default navbar-static-top">
  <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'mainsite:index' %}">
            <b>主页</b></a>
        <a class="navbar-brand" href="{% url 'mainsite:calculation' %}">
            上传图片并计算</a>
        <a class="navbar-brand" href="http://www.saas.sh.cn/">
            上海市农科院-站外链接</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>你好, {{ user.username}}.</a></li>
              <li><a href="{% url 'users:logout' %}">退出</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">登录</a></li>
              <li><a href="{% url 'users:register' %}">注册</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>


    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock header %}
      </div>
      <div>
        {% block content %}{% endblock content %}
      </div>
    </div> <!--/container-->

  </body>
</html>

bioweb/mainsite/templates/mainsite/cal_dia_centerline_width.html
{% extends "mainsite/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h1>请上传图片</h1>
  <p>可以上传1-5张图片，如果图片较多，请<a href="{% url 'mainsite:upload_compress_1' %}">
    点击此处上传rar或zip格式压缩包</p></a>

{% endblock header %}

{% block content %}
<form enctype="multipart/form-data" action=""
    method="post">
{% csrf_token %}
{{ form.as_p }}


    <input type="file" name="file_field" />
    <input type="file" name="file_field" />
    <input type="file" name="file_field" />
    <input type="file" name="file_field" />
    <input type="file" name="file_field" />



<br>

<p>点击提交按钮后请耐心等待页面跳转</p>
{% buttons %}
<button name="submit" class="btn btn-primary">提交</button>
{% endbuttons %}
</form>


{% endblock content %}

bioweb/mainsite/templates/mainsite/cal_dia_compress.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" context="IE=Edge">
    <meta name="Viewpoint" context="width=device-width, initial-scale=1">
    <title>香菇尺寸计算</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/docs.min.js"></script>
    <style>
        .progress-div{
            background: rgba(0, 0, 0, 0.03);
            width: 1000px;
            height: 140px;
            padding: 60px 20px;
            visibility: hidden;
        }
        .progress{
            margin: 0;
            /*position: fixed;*/
            /*top: 100px;*/
            /*left: 20px;*/
            width: 100%;
        }

    </style>
    <title>比例计算</title>
    {% load bootstrap3 %}
    {% load static %}


</head>

<body>

  <nav class="navbar navbar-default navbar-static-top">
  <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'mainsite:index' %}">
            <b>主页</b></a>
        <a class="navbar-brand" href="{% url 'mainsite:calculation' %}">
            上传图片并计算</a>
        <a class="navbar-brand" href="http://www.saas.sh.cn/">
            上海市农科院-站外链接</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>你好, {{ user.username}}.</a></li>
              <li><a href="{% url 'users:logout' %}">退出</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">登录</a></li>
              <li><a href="{% url 'users:register' %}">注册</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        <h1 id="heading">文件上传完成 点击按钮开始计算</h1>
      </div>
      <div>

        <br>
        <button name="submit"  class="btn btn-default"
        style="background-color: #376cb9; color: #ffffff">开始计算</button>
        <div  class="progress-div">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: 2%;">
                            2%
                        </div>
                    </div>
                    <br>
                     <div class="progress-text progress-bar-striped active"  role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: 2%;">
                     </div>
        </div>

        <table><tr>
        <td><img  src="?" id="vis_img_2" alt="index1" width="490" height="490" style="display:none; margin-right:20px";></td>
            <td><img  src="?"  id="vis_img_1" alt="index2" width="490" height="490" style="display:none;"></td>
        </tr></table>

      </div>
    </div> <!--/container-->

  </body>

<script>
 $(function () {

        $('.btn').on('click', function () {

                var log = ""
                var sitv = setInterval(function(){
                console.log("come in")
                      var prog_url = '/show_progress'              // prog_url指请求进度的url，后面会在django中设置
                      $.getJSON(prog_url, function(arg){

                          log = log + arg[0]+ "-"
                          $('.progress-div').css('visibility', 'visible');
                          $('.progress-bar').css('width', arg[0] + '%');
                          $('.progress-bar').text(arg[0] + '%');
                          var x = Number(arg[1])
                          var estimate = Math.floor(x/3600) + 'h ' + Math.floor(x/60)%60 + 'm ' + x%60 + 's';
                          $('.progress-text').text( '计算中... 预计剩余时间: ' + estimate);
                          $('.progress-text').css('width', '100%');


                          var vis_img_path_1 = "/static/vis/cache/" + "mid" + arg[2]
                          document.getElementById('vis_img_1').src = vis_img_path_1;
                          document.getElementById('vis_img_1').style.display ='block';

                          var vis_img_path_2 = "/static/vis/cache/" + "dia" + arg[2]
                          document.getElementById('vis_img_2').src = vis_img_path_2;
                          document.getElementById('vis_img_2').style.display ='block';

                    });
                }, 1000);                                 // 每10毫秒查询一次后台进度


                    var thisurl = '/cal/1/dia_compress_real'                      // 指当前页面的url
                    $.getJSON(thisurl ,function(res){
                    $('.progress-bar').css('width', '100%');
                    $('.progress-bar').text('100%');
                    //5秒后实现的方法写在这个方法里面
                    setTimeout(function() { window.location.href = '/cal/success'; }, 5 * 1000);
                    console.log("sitv over res"+res)
                        clearInterval(sitv);                   // 此时请求成功返回结果了，结束对后台进度的查询
            });
        })
})

</script>

</html>

bioweb/mainsite/templates/mainsite/cal_thick.html
{% extends "mainsite/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h1>请上传图片</h1>
<p>可以上传1-5张图片，如果图片较多，请<a href="{% url 'mainsite:upload_compress_2' %}">
    点击此处上传rar或zip格式压缩包</p></a>
{% endblock header %}

{% block content %}

<form enctype="multipart/form-data" action=""
    method="post">
{% csrf_token %}
{{ form.as_p }}

<input type="file" name="file_field" />
<input type="file" name="file_field" />
<input type="file" name="file_field" />
<input type="file" name="file_field" />
<input type="file" name="file_field" />
<br>

<p>点击提交按钮后请耐心等待页面跳转</p>

{% buttons %}
<button name="submit" class="btn btn-primary">提交</button>
{% endbuttons %}
</form>

{% endblock content %}

bioweb/mainsite/templates/mainsite/cal_thick_compress.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='utf-8'>
    <meta http-equiv="X-UA-Compatible" context="IE=Edge">
    <meta name="Viewpoint" context="width=device-width, initial-scale=1">
    <title>香菇尺寸计算</title>
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"></script>
    <script src="/static/js/bootstrap.min.js"></script>
    <script src="/static/js/docs.min.js"></script>
    <style>
        .progress-div{
            background: rgba(0, 0, 0, 0.03);
            width: 1000px;
            height: 140px;
            padding: 60px 20px;
            visibility: hidden;
        }
        .progress{
            margin: 0;
            /*position: fixed;*/
            /*top: 100px;*/
            /*left: 20px;*/
            width: 100%;
        }

    </style>
    <title>比例计算</title>
    {% load bootstrap3 %}
    {% load static %}


</head>

<body>

  <nav class="navbar navbar-default navbar-static-top">
  <div class="container">

      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
          data-toggle="collapse" data-target="#navbar"
          aria-expanded="false" aria-controls="navbar">
        </button>
        <a class="navbar-brand" href="{% url 'mainsite:index' %}">
            <b>主页</b></a>
        <a class="navbar-brand" href="{% url 'mainsite:calculation' %}">
            上传图片并计算</a>
        <a class="navbar-brand" href="http://www.saas.sh.cn/">
            上海市农科院-站外链接</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">

          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>你好, {{ user.username}}.</a></li>
              <li><a href="{% url 'users:logout' %}">退出</a></li>
            {% else %}
              <li><a href="{% url 'users:login' %}">登录</a></li>
              <li><a href="{% url 'users:register' %}">注册</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        <h1>文件上传完成</h1>
      </div>
      <div>

        <br>
        <button name="submit"  class="btn btn-default"
        style="background-color: #376cb9; color: #ffffff">开始计算</button>
        <div  class="progress-div">
                    <div class="progress">
                        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: 2%;">
                            2%
                        </div>
                    </div>
                    <br>
                     <div class="progress-text progress-bar-striped active"  role="progressbar" aria-valuenow="2" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: 2%;">
                     </div>
        </div>
      </div>
    </div> <!--/container-->

  </body>

<script>
 $(function () {

        $('.btn').on('click', function () {

                var log = ""
                var sitv = setInterval(function(){
                console.log("come in")
                      var prog_url = '/show_progress'              // prog_url指请求进度的url，后面会在django中设置
                      $.getJSON(prog_url, function(arg){

                          log = log + arg[0]+ "-"
                          $('.progress-div').css('visibility', 'visible');
                          $('.progress-bar').css('width', arg[0] + '%');
                          $('.progress-bar').text(arg[0] + '%');
                          var x = Number(arg[1])
                          var estimate = Math.floor(x/3600) + 'h ' + Math.floor(x/60)%60 + 'm ' + x%60 + 's';
                          $('.progress-text').text( '计算中... 预计剩余时间: ' + estimate);
                          $('.progress-text').css('width', '100%');

                    });
                }, 100);                                 // 每10毫秒查询一次后台进度


                    var thisurl = '/cal/2/thick_compress_real'                      // 指当前页面的url
                    $.getJSON(thisurl ,function(res){
                    $('.progress-bar').css('width', '100%');
                    $('.progress-bar').text('100%');
                    //5秒后实现的方法写在这个方法里面
                    setTimeout(function() { window.location.href = '/cal/success'; }, 5 * 1000);
                    console.log("sitv over res"+res)
                        clearInterval(sitv);                   // 此时请求成功返回结果了，结束对后台进度的查询
            });
        })
})

</script>

</html>

bioweb/mainsite/templates/mainsite/calculation.html
{% extends "mainsite/base.html" %}
{% load static %}
{% block header %}
    <h3>本站提供两种计算香菇尺寸的方式</h3>
{% endblock header %}


{% block content %}

  <div class="panel panel-default">
    <div class="panel-heading">
      <a href="{% url 'mainsite:cal1' %}"><h3>茎长、宽度和盖半径计算</h3></a>
    </div>
    <div class="panel-body">
      <p>请上传如下图所示的图片，需保证：香菇经方块的背景颜色为绿色，大方格尺寸为20cm×20cm作为标尺
        ，内部4个小方格为10cm×10cm</p>
      <img src="{% static "mainsite/cal_dia_sample_1.jpg" %}" alt="sample1"
      width="648" height="486">
    </div>
  </div><!--panel-->


  <div class="panel panel-default">
    <div class="panel-heading">
        <a href="{% url 'mainsite:cal2' %}"><h3>茎盖厚度计算</h3></a>
      </div>
      <div class="panel-body">
        <p>请上传如下图片</p>
        <img src="{% static "mainsite/cal_thick_sample.jpg" %}" alt="sample2"
        width="636" height="486" >
      </div>
    </div><!--panel-->

{% endblock content %}

bioweb/mainsite/templates/mainsite/index.html
{% extends "mainsite/base.html" %}
{% load static %}

{% block header %}
  <div class="jumbotron">
    <a href="{% url 'mainsite:calculation' %}">
    <h1>上传香菇图片并计算尺寸</h1></a>
  </div>
{% endblock header %}


{% block content %}


  <p>
    <b>使用说明</b>
    <br></br>
    上传按照要求拍摄好的香菇图片，自动计算出香菇各个特征尺寸：茎盖的半径和厚度、茎的中轴线长度及宽度
    <br></br>
    <b>样例图片</b>
    <br></br>
    <img src="{% static "mainsite/index_1.png" %}" alt="index1" width="375" height="375">
    <img src="{% static "mainsite/index_2.png" %}" alt="index2" width="375" height="375">
    <img src="{% static "mainsite/index_3.png" %}" alt="index3" width="375" height="375">
  </p>

{% endblock content %}

bioweb/mainsite/templates/mainsite/success.html
{% extends "mainsite/base.html" %}

{% load bootstrap3 %}

{% block header %}
<h1>计算成功！ 请下载结果</h1>
{% endblock header %}

{% block content %}
<a href="{% url 'mainsite:download' %}">
<button type="button" class="btn btn-success">下载结果</button>
</a>
{% endblock content %}